version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: library_Container
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: library_Container
      MYSQL_USER: test
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/abschlussprojekt/mysql

volumes:
  mysql-data:
    driver: local
